"use client";
import { useEffect, useState } from "react";
import contentful, { client } from "../../lib/contentful";
import Head from "next/head";
import {
  Grid,
  Card,
  CardContent,
  Typography,
  List,
  ListItem,
  ListItemText,
  Button,
  useTheme,
} from "@mui/material";
import stylesheet from "../styles/Home.module.css";
import { Actions, State } from "@/context/context";
import Certificate from "@/components/certificate";
import Solution from "@/components/solution";
import QuizCard from "@/components/QuizCard";
import Layout from "@/components/Layout";
import { PDFDownloadLink } from "@react-pdf/renderer";
import CertificateCreate from "@/components/pdf-generation/CertificateCreate";
import queries from "@/firebase/firestore/queries";
import CareerLandingView from "@/sections/_career/view/career-landing-view";
import MainLayout from "@/layouts/main";
// import CareerLandingView from "@/components/pageComponent/_career/view/career-landing-view";
export default function Home({ posts }) {
  const [quizes, setQuizes] = useState([]);
  const quizState = State();
  const theme = useTheme();
  const actions=Actions()
  useEffect(() => {
    setQuizes(posts);
    actions.quizReset();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CareerLandingView />
      <Button onClick={()=>{queries.createPdf("Subhan Akram","Listening Score","20/100","Reading Score","50/100","A-1 Beginners","40/100","24 Aug 2023")}}>Create pdf</Button>
    </>
  );
}
Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>;
};
export const getStaticProps = async () => {
  // const posts = await client.getEntries();
  // const posts = await contentful.getSingleBlogPost('quiz-B');

  const posts = await contentful.getEntryByContentType("levelC");

  return { props: { posts } };
};
