import Head from "next/head";
import stylesheet from "../styles/listening.module.css";
import Header from "@/components/header";
import ReadingQuestion from "@/components/readingQuestion";
import { useEffect, useRef, useState } from "react";
import PauseCircleOutlineOutlinedIcon from "@mui/icons-material/PauseCircleOutlineOutlined";
import PlayCircleOutlineOutlinedIcon from "@mui/icons-material/PlayCircleOutlineOutlined";
import { Actions, State } from "@/context/context";
import { Button, MobileStepper, useTheme } from "@mui/material";
import { KeyboardArrowLeft, KeyboardArrowRight } from "@mui/icons-material";
const options = ["Option 1", "Option 2", "Option 3", "Option 4"];

export default function FixedSideStepper({children}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${stylesheet.page_body} `}>
        <div>{children}</div>
        <div>
      </div>
      </div>
    </>
  );
}
