import Head from "next/head";
import stylesheet from "../styles/listening.module.css";
import Header from "@/components/header";
import ReadingQuestion from "@/components/readingQuestion";
import { useEffect, useRef, useState } from "react";
import PauseCircleOutlineOutlinedIcon from "@mui/icons-material/PauseCircleOutlineOutlined";
import PlayCircleOutlineOutlinedIcon from "@mui/icons-material/PlayCircleOutlineOutlined";
import { State } from "@/context/context";
const options = ["Option 1", "Option 2", "Option 3", "Option 4"];

export default function FixedSideComponent({ children, data }) {
  const audioRef = useRef(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [questionUrl, setQuestionUrl] = useState("");
  const quizState = State();
  const { quizInfo } = quizState;

  function formatTime(seconds) {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes.toString().padStart(2, "0")}:${remainingSeconds
      .toString()
      .padStart(2, "0")}`;
  }
  //   const getActiveStepQuestion = () => {
  //     const getQuestionAudioUrl =
  //       data.audioList[quizInfo["activeStep"]]?.fields?.file?.url;
  //     setQuestionUrl(`http:${getQuestionAudioUrl}`);
  //     return `http:${getQuestionAudioUrl}`;
  //   };
  //   useEffect(() => {
  //     getActiveStepQuestion();
  //   }, [quizInfo["activeStep"]]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={stylesheet.page_body}>
        <div className={stylesheet.grid}>{children}</div>
      </div>
    </>
  );
}
