import Head from "next/head";
import stylesheet from "../styles/listening.module.css";
import { useEffect } from "react";
import TopSliderDrawer from "./TopSlideDrawer";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";



export default function FixedSideStepper({children,longPhrase}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopSliderDrawer ><div style={{overflowY:"scroll"}}>{documentToReactComponents(longPhrase)}</div></TopSliderDrawer>
      <div className={`${stylesheet.page_body} `}>
        <div>{children}</div>
        <div>
      </div>
      </div>
    </>
  );
}
