import Head from "next/head";
import stylesheet from "../styles/GridQuestion.module.css";
import {
  Card,
  CardContent,
  Checkbox,
  FormControl,
  FormControlLabel,
  Radio,
  RadioGroup,
  Typography,
} from "@mui/material";
import { useState } from "react";

export default function GridQuestion() {
  const [selectedOption, setSelectedOption] = useState("");

  const handleOptionChange = (event) => {
    setSelectedOption(event.target.value);
  };

  const options = ['hello 1', 'hello 2', 'hello 3']

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card className={stylesheet.card}>
        <CardContent>
          <p className={stylesheet.ques}>The passage explains how the carnival started.</p>
          <FormControl component="fieldset" className={stylesheet.optionBx}>
            <RadioGroup style={{ display: 'flex', flexDirection: 'row' }} value={selectedOption} onChange={handleOptionChange}>
              {options.map((option, index) => (
                <FormControlLabel
                  key={index}
                  value={option}
                  control={
                    <Radio
                        style={{display: 'mone'}}
                        className={[
                            selectedOption === option ? stylesheet.selected : "",
                        ]}
                    />
                  }
                  label={option}
                  className={[
                    stylesheet.option,
                    selectedOption === option ? stylesheet.selected : "",
                  ]}
                />
              ))}
            </RadioGroup>
          </FormControl>
        </CardContent>
      </Card>
    </>
  );
}
