import Head from "next/head";
import stylesheet from "../styles/header.module.css";
import {
  AppBar,
  
  Toolbar,

} from "@mui/material";
import React, { useState } from "react";
import { makeStyles } from "@mui/styles";
import Image from "next/image";

const useStyles = makeStyles((theme) => {
  return {};
});

export default function Header() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="fixed" className={stylesheet.header}>
        <Toolbar
          className={`${stylesheet.headerTool}`}
        >
        <Image width={100} height={24} alt="logo" src={"https://a.storyblok.com/f/71234/103x24/da9ab91cbd/efset-logo_black.svg"} />
        </Toolbar>
      </AppBar>
    </>
  );
}
