import Head from "next/head";
import stylesheet from "../styles/header.module.css";
import {
  AppBar,
  Avatar,
  Box,
  IconButton,
  MenuItem,
  Toolbar,
  Tooltip,
  Typography,
} from "@mui/material";
import MenuIcon from '@mui/icons-material/Menu';
import React, { useState } from "react";
import { makeStyles } from "@mui/styles";
import Menu from "./menu/Menu";
import useWindowWidth from "@/hooks/useCurrentWidth";
import { Close } from "@mui/icons-material";
import { State } from "@/context/context";

const useStyles = makeStyles((theme) => {
  return {};
});

export default function Header() {
  const [anchorElUser, setAnchorElUser] = React.useState(null);
  const [openHamburger, setOpenHamburger] = useState(false);
  const currentWidth = useWindowWidth();
  const handleOpenUserMenu = (event) => {
    setAnchorElUser(event.currentTarget);
  };
  const pageLoad = State();

  const handleCloseUserMenu = () => {
    setAnchorElUser(null);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar className={stylesheet.header}>
        <Toolbar  className={`${currentWidth < 900 && openHamburger ?stylesheet.responsive_headerTool:stylesheet.headerTool}`}>
          <h1 className={`${
                currentWidth < 900 && openHamburger ?stylesheet.menu_hide:stylesheet.logo}`}>
            <i>EF</i>
            <span>SET</span>
          </h1>
          <div
              className={`${
                currentWidth < 900   && openHamburger?stylesheet.menu_hide: stylesheet.hamburger 
              }`}
              onClick={()=>{setOpenHamburger(!openHamburger)}}
            >
             <MenuIcon style={{color:"black",}} />
            </div>
          <div style={{  left:'0',
    display: 'flex',
     left: openHamburger ? '0%' : '-120%' }} className={`${currentWidth < 900 && openHamburger ?stylesheet.responsive_menu:stylesheet.menu} `}>
          <div
              className={`${
                currentWidth < 900 && openHamburger? stylesheet.hamburger : stylesheet.menu_hide
              }`}
              onClick={()=>{setOpenHamburger(!openHamburger)}}
            >
              <Close />
            </div>
            <Box sx={{ flexGrow: 0 }}>
              <Menu
                title="Certification"
                options={["profile", "user", "setting"]}
              />
            </Box>
            <Box sx={{ flexGrow: 0 }}>
              <Menu title="CEFBR" options={["profile", "user", "setting"]} />
            </Box>
            <Box sx={{ flexGrow: 0 }}>
              <Menu title="About Us" options={["profile", "user", "setting"]} />
            </Box>
          </div>
        </Toolbar>
      </AppBar>
     
    </>
  );
}
