import Head from 'next/head'
import Image from 'next/image'
import stylesheet from '../styles/quizInfo.module.css'
import { Card, CardContent } from '@mui/material'
import Book from "../assets/book.svg"
import listening from "../assets/listening.svg"
import totalMarks from "../assets/total_score.svg" 
const options = ['Option 1', 'Option 2', 'Option 3', 'Option 4'];


export default function QuizInfo({startQuiz,isQuiz,category}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={stylesheet.page_body}>
      
        <div className={stylesheet.container}>
        <Card className={stylesheet.card}>
          <CardContent className={stylesheet.card__content}>
            <h1>Welcome, you are about to start the {isQuiz?50:15}-minute Quick English Check</h1>
            <div className={stylesheet.icon_bx}>
              <div className={stylesheet.icon_elem}>
                <Image
                 alt="book"
                  src={Book}
                  width={60.97}
                  height={50.8}
                />
                <p>reading</p>
                <p>{isQuiz?25.5:7.5} mins</p>
              </div>
              <span>+</span>
              <div className={stylesheet.icon_elem}>
                <Image
                 alt="audio"
                  src={listening}
                  width={60.97}
                  height={50.8}
                />
                <p>Listening</p>
                <p>{isQuiz?25.5:7.5} mins</p>
              </div>
              <span>=</span>
              <div className={stylesheet.icon_elem}>
                <Image
                 alt="total marks"
                  src={totalMarks}
                  width={60.97}
                  height={50.8}
                />
                <p>Total Time</p>
                <p>{isQuiz?50:15} mins</p>
              </div>
            </div>
            <ul className={stylesheet.list__item}>
              <li>This test has two sections: reading and listening</li>
              <li>You will start with a 7.5-minute reading section.</li>
              <li>Pace yourself to avoid running out of time.</li>
              <li>You will not lose points for wrong answers.</li>
              <li>Once you click "Next" you cannot go back.</li>
              <li>Take advantage of the  "Full-screen" mode for an optimal test experience. You can always find this icon in the bottom-right corner of your screen.</li>
            </ul>
            <div className={stylesheet.btn} >
              <button className={stylesheet.take__quizBtn} onClick={startQuiz}>Start the quiz</button>
            </div>
            <hr style={{marginTop:"2rem"}} />
          </CardContent>
        </Card>
        </div>
      </div>
    </>
  )
}
