import Head from "next/head";
import stylesheet from "../styles/readingQuestion.module.css";
import {
  Card,
  CardContent,
  Checkbox,
  FormControl,
  FormControlLabel,
  Radio,
  RadioGroup,
  Typography,
} from "@mui/material";
import { useState } from "react";
import Solution from "./solution";
import Certificate from "./certificate";
import { useMediaQuery } from "@mui/material";
import useAnswerCheck from "@/hooks/useAnswerCheck";
import { Actions, State } from "@/context/context";
import GlobalFunctions from "../../lib/GlobalFunctions";
import RadioOptions from "./options/RadioOptions";
import CheckboxOptions from "./options/CheckboxOptions";
import DropdownOptions from "./options/DropdownOptions";

const scoreCollection = [];
export default function ReadingQuestion({
  question,
  options,
  allInfo,
  questionCategory,
  userQuizHandler,
  id,
}) {
  const [selectedOption, setSelectedOption] = useState("");
  console.log("all info", allInfo);
  const handleOptionChange = (event) => {
    setSelectedOption(event.target.value);
    let givenAnswer = event.target.value;
    let score = givenAnswer === allInfo.answer ? 10 : 0;
    userQuizHandler({
      answer: allInfo.answer,
      givenAnswer,
      score,
      questionCategory,
      id,
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card className={stylesheet.card}>
        <CardContent>
          <p
            className={stylesheet.ques}
            onCopy={GlobalFunctions.handleCopyPaste}
            onPaste={GlobalFunctions.handleCopyPaste}
          >
            {question}
          </p>
          {allInfo.type === "checkbox" && (
            <CheckboxOptions
              options={options}
              handleOptionChange={handleOptionChange}
              selectedOption={selectedOption}
            />
          )}
          {allInfo.type !== "checkbox" && allInfo.type !=="dropdown" && (
            <RadioOptions
              options={options}
              handleOptionChange={handleOptionChange}
              selectedOption={selectedOption}
            />
          )}
          {allInfo.type ==="dropdown" && (
             <DropdownOptions
             options={options}
             handleOptionChange={handleOptionChange}
             selectedOption={selectedOption}
           />
          )}
        </CardContent>
      </Card>
    </>
  );
}
