import Head from "next/head";
import stylesheet from "../styles/readingQuestion.module.css";
import {
  Card,
  CardContent,
  Checkbox,
  FormControl,
  FormControlLabel,
  Radio,
  RadioGroup,
  Typography,
} from "@mui/material";
import { useState } from "react";
import GlobalFunctions from "../../lib/GlobalFunctions";

const scoreCollection = [];
export default function ReadingQuestion({
  question,
  options,
  allInfo,
  questionCategory,
  userQuizHandler,
  id,
}) {
  const [selectedOption, setSelectedOption] = useState("");

  const handleOptionChange = (event) => {
    setSelectedOption(event.target.value);
    let givenAnswer = event.target.value;
    let score = givenAnswer === allInfo.answer ? 10 : 0;
    userQuizHandler({
      answer: allInfo.answer,
      givenAnswer,
      score,
      questionCategory,
      id,
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card className={stylesheet.card}>
        <CardContent>
          <p className={stylesheet.question} onCopy={GlobalFunctions.handleCopyPaste} onPaste={GlobalFunctions.handleCopyPaste}>{question}</p>
          <FormControl component="fieldset" className={stylesheet.optionBx}>
            <RadioGroup value={selectedOption} onChange={handleOptionChange}>
              {options.map((option, index) => (
                <FormControlLabel
                  key={index}
                  value={option}
                  control={
                    <Radio
                      className={
                        selectedOption === option ? stylesheet.selected : ""
                      }
                    />
                  }
                  label={option}
                  className={[
                    stylesheet.option,
                    selectedOption === option ? stylesheet.selected : "",
                  ]}
                  // className={selectedOption === option ? stylesheet.selected : ''}
                />
              ))}
            </RadioGroup>
          </FormControl>
        </CardContent>
      </Card>
    </>
  );
}
